name: Build Examples

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build-console-examples:
    name: Build Console Examples
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release, Debug]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          ninja-build \
          libboost-all-dev \
          pkg-config \
          wget \
          software-properties-common \
          lsb-release
        # Install newer CMake version
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
        sudo apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"
        sudo apt-get update
        sudo apt-get install -y cmake
          
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install cmake ninja boost pkg-config
        
    - name: Setup MSVC (Windows)
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1
      
    - name: Create build directory
      run: mkdir build
      
    - name: Configure CMake (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        cd build
        cmake .. \
          -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DBUILD_CONSOLE_APPLICATION=ON \
          -DBUILD_VIEWER_APPLICATION=OFF \
          -DCMAKE_INSTALL_PREFIX=install \
          -DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations" \
          -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
          -Wno-dev
          
    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd build
        cmake .. `
          -G "Visual Studio 17 2022" `
          -A x64 `
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} `
          -DBUILD_CONSOLE_APPLICATION=ON `
          -DBUILD_VIEWER_APPLICATION=OFF `
          -DCMAKE_INSTALL_PREFIX=install `
          -DCMAKE_POLICY_VERSION_MINIMUM=3.5 `
          -Wno-dev
          
    - name: Build console examples
      run: |
        cd build
        cmake --build . --config ${{ matrix.build_type }} --target CreateIfcWallAndWriteFile
        cmake --build . --config ${{ matrix.build_type }} --target LoadFileExample
        
    - name: Test console examples (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        cd build
        ls -la ${{ matrix.build_type }}/
        file ${{ matrix.build_type }}/CreateIfcWallAndWriteFile || true
        file ${{ matrix.build_type }}/LoadFileExample || true
        
    - name: Test console examples (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd build
        dir ${{ matrix.build_type }}\
        if (Test-Path "${{ matrix.build_type }}\CreateIfcWallAndWriteFile.exe") { Write-Host "CreateIfcWallAndWriteFile.exe found" }
        if (Test-Path "${{ matrix.build_type }}\LoadFileExample.exe") { Write-Host "LoadFileExample.exe found" }
        
    - name: Upload console examples artifacts
      uses: actions/upload-artifact@v4
      with:
        name: console-examples-${{ matrix.os }}-${{ matrix.build_type }}
        path: |
          build/${{ matrix.build_type }}/CreateIfcWallAndWriteFile*
          build/${{ matrix.build_type }}/LoadFileExample*
        retention-days: 7

  build-json-renderer:
    name: Build JSON Net Renderer
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          ninja-build \
          libboost-all-dev \
          pkg-config \
          git
          
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install cmake ninja boost pkg-config git
        
    - name: Setup MSVC (Windows)
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1
      
    - name: Create build directory
      run: mkdir build
      
    - name: Configure CMake (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        cd build
        cmake .. \
          -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DBUILD_CONSOLE_APPLICATION=ON \
          -DBUILD_VIEWER_APPLICATION=OFF \
          -DCMAKE_INSTALL_PREFIX=install \
          -DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations" \
          -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
          -Wno-dev
          
    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd build
        cmake .. `
          -G "Visual Studio 17 2022" `
          -A x64 `
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} `
          -DBUILD_CONSOLE_APPLICATION=ON `
          -DBUILD_VIEWER_APPLICATION=OFF `
          -DCMAKE_INSTALL_PREFIX=install `
          -DCMAKE_POLICY_VERSION_MINIMUM=3.5 `
          -Wno-dev
          
    - name: Build JSON Net Renderer
      run: |
        cd build
        cmake --build . --config ${{ matrix.build_type }} --target IfcJsonNetRenderer
        
    - name: Upload JSON renderer artifacts
      uses: actions/upload-artifact@v4
      with:
        name: json-renderer-${{ matrix.os }}-${{ matrix.build_type }}
        path: |
          build/${{ matrix.build_type }}/IfcJsonNetRenderer*
        retention-days: 7

  build-summary:
    name: Build Summary
    needs: [build-console-examples, build-json-renderer]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Check build results
      run: |
        echo "Console Examples Build: ${{ needs.build-console-examples.result }}"
        echo "JSON Renderer Build: ${{ needs.build-json-renderer.result }}"
        
        if [[ "${{ needs.build-console-examples.result }}" == "success" ]]; then
          echo "✅ Console examples built successfully"
        else
          echo "❌ Console examples build failed"
        fi
        
        if [[ "${{ needs.build-json-renderer.result }}" == "success" ]]; then
          echo "✅ JSON renderer built successfully"
        else
          echo "❌ JSON renderer build failed"
        fi